#compiler
CC = gcc

# Compile options. Το -I<dir> λέει στον compiler να αναζητήσει εκεί include files
CFLAGS = -Wall  -g -I ./Include

# Αρχεία .o
OBJ_RECEPTIONIST = receptionist.o
OBJ_VISITOR = visitor.o
OBJ_MONITOR = monitor.o

# Το εκτελέσιμο πρόγραμμα
EXEC_RECEPTIONIST = receptionist
EXEC_VISITOR = visitor
EXEC_MONITOR = monitor


clean:
	rm -f $(OBJ_RECEPTIONIST) $(OBJ_VISITOR) $(OBJ_MONITOR) $(EXEC_RECEPTIONIST) $(EXEC_VISITOR) $(EXEC_MONITOR) 
